// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: trie.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrieService_Add_FullMethodName    = "/trie.TrieService/Add"
	TrieService_Remove_FullMethodName = "/trie.TrieService/Remove"
	TrieService_Check_FullMethodName  = "/trie.TrieService/Check"
	TrieService_List_FullMethodName   = "/trie.TrieService/List"
)

// TrieServiceClient is the client API for TrieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrieServiceClient interface {
	Add(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Remove(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	Check(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error)
}

type trieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrieServiceClient(cc grpc.ClientConnInterface) TrieServiceClient {
	return &trieServiceClient{cc}
}

func (c *trieServiceClient) Add(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TrieService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trieServiceClient) Remove(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, TrieService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trieServiceClient) Check(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, TrieService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trieServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, TrieService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrieServiceServer is the server API for TrieService service.
// All implementations must embed UnimplementedTrieServiceServer
// for forward compatibility.
type TrieServiceServer interface {
	Add(context.Context, *WordRequest) (*StatusResponse, error)
	Remove(context.Context, *WordRequest) (*CheckResponse, error)
	Check(context.Context, *WordRequest) (*StatusResponse, error)
	List(context.Context, *Empty) (*ListResponse, error)
	mustEmbedUnimplementedTrieServiceServer()
}

// UnimplementedTrieServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrieServiceServer struct{}

func (UnimplementedTrieServiceServer) Add(context.Context, *WordRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedTrieServiceServer) Remove(context.Context, *WordRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedTrieServiceServer) Check(context.Context, *WordRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedTrieServiceServer) List(context.Context, *Empty) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTrieServiceServer) mustEmbedUnimplementedTrieServiceServer() {}
func (UnimplementedTrieServiceServer) testEmbeddedByValue()                     {}

// UnsafeTrieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrieServiceServer will
// result in compilation errors.
type UnsafeTrieServiceServer interface {
	mustEmbedUnimplementedTrieServiceServer()
}

func RegisterTrieServiceServer(s grpc.ServiceRegistrar, srv TrieServiceServer) {
	// If the following call panics, it indicates UnimplementedTrieServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrieService_ServiceDesc, srv)
}

func _TrieService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrieServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrieService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrieServiceServer).Add(ctx, req.(*WordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrieService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrieServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrieService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrieServiceServer).Remove(ctx, req.(*WordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrieService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrieServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrieService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrieServiceServer).Check(ctx, req.(*WordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrieService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrieServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrieService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrieServiceServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TrieService_ServiceDesc is the grpc.ServiceDesc for TrieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trie.TrieService",
	HandlerType: (*TrieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TrieService_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _TrieService_Remove_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _TrieService_Check_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TrieService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trie.proto",
}
