// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: trie.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordRequest) Reset() {
	*x = WordRequest{}
	mi := &file_trie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRequest) ProtoMessage() {}

func (x *WordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRequest.ProtoReflect.Descriptor instead.
func (*WordRequest) Descriptor() ([]byte, []int) {
	return file_trie_proto_rawDescGZIP(), []int{0}
}

func (x *WordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_trie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_trie_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_trie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_trie_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []string               `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"` // 'repeated' becomes a slice []string in Go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_trie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_trie_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_trie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_trie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_trie_proto_rawDescGZIP(), []int{4}
}

var File_trie_proto protoreflect.FileDescriptor

const file_trie_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"trie.proto\x12\x04trie\"!\n" +
	"\vWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\rCheckResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"$\n" +
	"\fListResponse\x12\x14\n" +
	"\x05words\x18\x01 \x03(\tR\x05words\"\a\n" +
	"\x05Empty2\xca\x01\n" +
	"\vTrieService\x12.\n" +
	"\x03Add\x12\x11.trie.WordRequest\x1a\x14.trie.StatusResponse\x120\n" +
	"\x06Remove\x12\x11.trie.WordRequest\x1a\x13.trie.CheckResponse\x120\n" +
	"\x05Check\x12\x11.trie.WordRequest\x1a\x14.trie.StatusResponse\x12'\n" +
	"\x04List\x12\v.trie.Empty\x1a\x12.trie.ListResponseB\tZ\a./protob\x06proto3"

var (
	file_trie_proto_rawDescOnce sync.Once
	file_trie_proto_rawDescData []byte
)

func file_trie_proto_rawDescGZIP() []byte {
	file_trie_proto_rawDescOnce.Do(func() {
		file_trie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trie_proto_rawDesc), len(file_trie_proto_rawDesc)))
	})
	return file_trie_proto_rawDescData
}

var file_trie_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_trie_proto_goTypes = []any{
	(*WordRequest)(nil),    // 0: trie.WordRequest
	(*StatusResponse)(nil), // 1: trie.StatusResponse
	(*CheckResponse)(nil),  // 2: trie.CheckResponse
	(*ListResponse)(nil),   // 3: trie.ListResponse
	(*Empty)(nil),          // 4: trie.Empty
}
var file_trie_proto_depIdxs = []int32{
	0, // 0: trie.TrieService.Add:input_type -> trie.WordRequest
	0, // 1: trie.TrieService.Remove:input_type -> trie.WordRequest
	0, // 2: trie.TrieService.Check:input_type -> trie.WordRequest
	4, // 3: trie.TrieService.List:input_type -> trie.Empty
	1, // 4: trie.TrieService.Add:output_type -> trie.StatusResponse
	2, // 5: trie.TrieService.Remove:output_type -> trie.CheckResponse
	1, // 6: trie.TrieService.Check:output_type -> trie.StatusResponse
	3, // 7: trie.TrieService.List:output_type -> trie.ListResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trie_proto_init() }
func file_trie_proto_init() {
	if File_trie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trie_proto_rawDesc), len(file_trie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trie_proto_goTypes,
		DependencyIndexes: file_trie_proto_depIdxs,
		MessageInfos:      file_trie_proto_msgTypes,
	}.Build()
	File_trie_proto = out.File
	file_trie_proto_goTypes = nil
	file_trie_proto_depIdxs = nil
}
