apiVersion: v1
kind: Pod
metadata:
  name: trie-server
  labels:
    app: trie-server
spec:
  containers:
  - name: trie-server
    image: localhost/trie-server:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 50051