FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /server_bin server/main.go
RUN go build -o /client_bin client/main.go

FROM alpine:latest AS server
WORKDIR /root/
COPY --from=builder /server_bin ./server
EXPOSE 50051
CMD ["./server"]
