syntax = "proto3";
 
option go_package = "./proto";

package trie;

service TrieService {
    rpc Add(WordRequest) returns (StatusResponse);
    rpc Remove(WordRequest) returns (CheckResponse);
    rpc Check(WordRequest) returns (StatusResponse);
    rpc List(Empty) returns (ListResponse);
}

message WordRequest {
  string word = 1;
}

message StatusResponse {
  bool success = 1;
}

message CheckResponse {
  bool exists = 1;
}

message ListResponse {
  repeated string words = 1; // 'repeated' becomes a slice []string in Go
}

message Empty {}